---
- name: Get cpu usage
  ansible.windows.win_shell: Get-WmiObject Win32_Processor | Select LoadPercentage | Format-List
  register: cpu_usage

- name: Display cpu usage
  ansible.builtin.debug:
    msg: "{{ cpu_usage.stdout | trim }}"